import ArrayList from "./src/code/list/ArrayList";
import SingleLinkedList from "./src/code/list/SingleLinkedList";
import SingleLinkedList2 from "./src/code/list/SingleLinkedList2";
import DuLinkedList from "./src/code/list/DuLinkedList";
import SingleCircleLinkedList from "./src/code/list/SingleCircleLinkedList";
import DuCircleLinkedList from "./src/code/list/DuCircleLinkedList";
import Stack from "./src/code/stack/Stack";
import Queue from "./src/code/queue/Queue";
import Deque from "./src/code/queue/Deque";
import CircleQueue from "./src/code/queue/CircleQueue";
import CircleDeque from "./src/code/queue/CircleDeque";
import BinaryTree from "./src/code/tree/BinaryTree";
import AVLTree from "./src/code/tree/AVLTree";
import IList from "./src/code/list/IList";
const temp: IList<number> = new SingleLinkedList<number>();
temp.add();
